spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/weekly_report_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:didulapostgre123}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

